// 顶部菜单栏
export const MAIN_HEADER_SELECTED_ITEM = 'MAIN_HEADER_SELECTED_ITEM'
// 侧边栏
export const MAIN_SIDEBAR_SELECTED_DEVICEID = 'MAIN_SIDEBAR_SELECTED_DEVICEID'

// 点位列表点击记录
export const CONTENT_SELECTED_DEVICE = 'CONTENT_SELECTED_DEVICE'
export const CONTENT_SELECTED_GROUP = 'CONTENT_SELECTED_GROUP'
export const CONTENT_SELECTED_GROUPID = 'CONTENT_SELECTED_GROUPID'
// export const CONTENT_GROUP_SELECTED_FIRST = 'CONTENT_GROUP_SELECTED_FIRST'

